--
-- VHDL Test Bench my_project1_lib.half_adder_tester.half_adder_tester
--
-- Created:
--          by - Techlabs.UNKNOWN (DESKTOP-D382P7A)
--          at - 13:38:31 04-03-2024
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2023.3 Built on 9 Jul 2023 at 00:00:47
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;


ENTITY half_adder_tester IS
   PORT (
      a     : OUT    std_logic;
      b     : OUT    std_logic;
      sum   : IN     std_logic;
      carry : IN     std_logic
   );
END half_adder_tester;


LIBRARY my_project1_lib;

ARCHITECTURE rtl OF half_adder_tester IS
   -- Architecture declarations
BEGIN
END rtl;
