--
-- VHDL Test Bench my_project1_lib.half_adder_tb.half_adder_tester
--
-- Created:
--          by - Techlabs.UNKNOWN (DESKTOP-D382P7A)
--          at - 13:38:31 04-03-2024
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2023.3 Built on 9 Jul 2023 at 00:00:47
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;


ENTITY half_adder_tb IS
END half_adder_tb;


LIBRARY my_project1_lib;
USE my_project1_lib.ALL;


ARCHITECTURE rtl OF half_adder_tb IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL a     : std_logic;
   SIGNAL b     : std_logic;
   SIGNAL sum   : std_logic;
   SIGNAL carry : std_logic;


   -- Component declarations
   COMPONENT half_adder
      PORT (
         a     : IN     std_logic;
         b     : IN     std_logic;
         sum   : OUT    std_logic;
         carry : OUT    std_logic
      );
   END COMPONENT;

   COMPONENT half_adder_tester
      PORT (
         a     : OUT    std_logic;
         b     : OUT    std_logic;
         sum   : IN     std_logic;
         carry : IN     std_logic
      );
   END COMPONENT;

   -- embedded configurations
   -- pragma synthesis_off
   FOR U_0 : half_adder USE ENTITY my_project1_lib.half_adder;
   FOR U_1 : half_adder_tester USE ENTITY my_project1_lib.half_adder_tester;
   -- pragma synthesis_on

BEGIN

         U_0 : half_adder
            PORT MAP (
               a     => a,
               b     => b,
               sum   => sum,
               carry => carry
            );

         U_1 : half_adder_tester
            PORT MAP (
               a     => a,
               b     => b,
               sum   => sum,
               carry => carry
            );


END rtl;