--
-- VHDL Test Bench my_project1_lib.xnor_gate_tb.xnor_gate_tester
--
-- Created:
--          by - Techlabs.UNKNOWN (DESKTOP-D382P7A)
--          at - 13:47:34 04-03-2024
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2023.3 Built on 9 Jul 2023 at 00:00:47
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;


ENTITY xnor_gate_tb IS
END xnor_gate_tb;


LIBRARY my_project1_lib;
USE my_project1_lib.ALL;


ARCHITECTURE rtl OF xnor_gate_tb IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL input1 : std_logic;
   SIGNAL input2 : std_logic;
   SIGNAL output : std_logic;


   -- Component declarations
   COMPONENT xnor_gate
      PORT (
         input1 : IN     std_logic;
         input2 : IN     std_logic;
         output : OUT    std_logic
      );
   END COMPONENT;

   COMPONENT xnor_gate_tester
      PORT (
         input1 : OUT    std_logic;
         input2 : OUT    std_logic;
         output : IN     std_logic
      );
   END COMPONENT;

   -- embedded configurations
   -- pragma synthesis_off
   FOR U_0 : xnor_gate USE ENTITY my_project1_lib.xnor_gate;
   FOR U_1 : xnor_gate_tester USE ENTITY my_project1_lib.xnor_gate_tester;
   -- pragma synthesis_on

BEGIN

         U_0 : xnor_gate
            PORT MAP (
               input1 => input1,
               input2 => input2,
               output => output
            );

         U_1 : xnor_gate_tester
            PORT MAP (
               input1 => input1,
               input2 => input2,
               output => output
            );


END rtl;