--
-- VHDL Test Bench my_project1_lib.xnor_gate_tester.xnor_gate_tester
--
-- Created:
--          by - Techlabs.UNKNOWN (DESKTOP-D382P7A)
--          at - 13:47:34 04-03-2024
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2023.3 Built on 9 Jul 2023 at 00:00:47
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;


ENTITY xnor_gate_tester IS
   PORT (
      input1 : OUT    std_logic;
      input2 : OUT    std_logic;
      output : IN     std_logic
   );
END xnor_gate_tester;


LIBRARY my_project1_lib;

ARCHITECTURE rtl OF xnor_gate_tester IS
   -- Architecture declarations
BEGIN
END rtl;
